-- esmeraldo
-- desenvolve
-- jonata
-- producao

-- 08/12/2017

INSERT INTO `db_pir_grc`.`grc_parametros` (`codigo`, `descricao`, `ativo`, `html`, `detalhe`, `classificacao`) VALUES ('evento_declaracao_modelo_cont', 'Modelo da Declaração na Prestação de Contas do Evento', 'S', 'S', '<p><style type=\"text/css\">\r\n    div.tit {\r\n        text-align: center;\r\n        font-size: 18px;\r\n        font-weight: bold;\r\n        padding-top: 60px;\r\n    }\r\n    \r\n    div.txt1 {\r\n        font-size: 14px;\r\n        padding-top: 80px;\r\n    }\r\n    \r\n    div.txt2 {\r\n        text-align: right;\r\n        font-size: 14px;\r\n        padding-top: 80px;\r\n        font-weight: bold;\r\n    }\r\n</style></p>\r\n<div class=\"tit\">DECLARA&Ccedil;&Atilde;O DE CONCLUS&Atilde;O DOS SERVI&Ccedil;OS</div>\r\n<div class=\"txt1\">Eu, #nome_gerente#, matr&iacute;cula n&ordm; #matricula#, no uso das atribui&ccedil;&otilde;es  do cargo de #cargo#, declaro para os devidos fins, que o(s)  material(is) e/ou servi&ccedil;o(s) correspondente(s) ao evento N&ordm; #codigo_evento#,  Ordem(ns) de Servi&ccedil;o(s) N&ordm; #codigo_os#, foi(ram) recebido(s) e/ou  prestado(s), liberando-se o processo para pagamento.</div>\r\n<div class=\"txt2\">#cidade#, #estado#, #dt_aprovacao#.</div>', '02.06');
INSERT INTO `db_pir_grc`.`grc_parametros` (`codigo`, `descricao`, `ativo`, `html`, `detalhe`, `classificacao`) VALUES ('evento_declaracao_modelo_cab', 'Modelo da Declaração na Prestação de Contas do Evento (Cabeçalho)', 'S', 'S', '<div style=\"text-align: center;\"><br />\r\n<img src=\"http://pir.ba.sebrae.com.br/sebrae_grc/admin/imagens/rel_logo_sebrae.png\" alt=\"\" /></div>', '02.07');
INSERT INTO `db_pir_grc`.`grc_parametros` (`codigo`, `descricao`, `ativo`, `html`, `detalhe`, `classificacao`) VALUES ('evento_declaracao_modelo_rod', 'Modelo da Declaração na Prestação de Contas do Evento (Rodape)', 'S', 'S', '<p><style type=\"text/css\">\r\n    div.footer_txt1 {\r\n        font-size: 12px;\r\n        font-style: italic;\r\n    }\r\n\r\n    div.footer_txt2 {\r\n        text-align: right;\r\n        font-size: 12px;\r\n        font-style: italic;\r\n        padding-top: 20px;\r\n        padding-bottom: 20px;\r\n    }\r\n</style></p>\r\n<div class=\"footer_txt1\">Este &eacute; um documento gerado eletronicamente pelo Sistema de Gest&atilde;o de Finan&ccedil;as GFI, ap&oacute;s a  <b>autoriza&ccedil;&atilde;o de pagamento</b>, realizada pelo Gerente/Adjunto da Unidade Regional respons&aacute;vel pela realiza&ccedil;&atilde;o do evento.</div>\r\n<div class=\"footer_txt2\">C&oacute;digo de Autenticidade: #md5#</div>\r\n<div style=\"text-align: center;\"><img src=\"http://pir.ba.sebrae.com.br/sebrae_grc/admin/imagens/rel_rodape.png\" alt=\"\" /></div>', '02.08');

INSERT INTO `db_pir_grc`.`plu_config` (`variavel`, `descricao`, `valor`, `extra`, `js`, `classificacao`) VALUES ('evento_upload_os', 'Fazer o Upload da Ordem de Serviço na Prestação de Contas do Evento?', 'Não', NULL, 'N', NULL);

ALTER TABLE `grc_evento`
ADD COLUMN `arq_ordem_servico`  varchar(255) NULL AFTER `nao_sincroniza_rm`;

-- 19/12/2017

ALTER TABLE `grc_evento_declaracao`
ADD COLUMN `tipo`  char(2) NOT NULL DEFAULT 'GE' AFTER `idt_pfo_af_processo`;

update grc_parametros set codigo = 'evento_declaracao_modelo_ge_cont', descricao = 'Modelo da Declaração na Prestação de Contas pelo Gestor no Evento' where codigo = 'evento_declaracao_modelo_cont';
update grc_parametros set codigo = 'evento_declaracao_modelo_ge_cab', descricao = 'Modelo da Declaração na Prestação de Contas pelo Gestor no Evento (Cabeçalho)' where codigo = 'evento_declaracao_modelo_cab';
update grc_parametros set codigo = 'evento_declaracao_modelo_ge_rod', descricao = 'Modelo da Declaração na Prestação de Contas pelo Gestor no Evento (Rodape)' where codigo = 'evento_declaracao_modelo_rod';

INSERT INTO `db_pir_grc`.`grc_parametros` (`codigo`, `descricao`, `ativo`, `html`, `detalhe`, `classificacao`) VALUES ('evento_declaracao_modelo_re_cont', 'Modelo da Declaração na Prestação de Contas pelo Responsável do Evento', 'S', 'S', '<p><style type=\"text/css\">\r\n    div.tit {\r\n        text-align: center;\r\n        font-size: 18px;\r\n        font-weight: bold;\r\n        padding-top: 60px;\r\n    }\r\n    \r\n    div.txt1 {\r\n        font-size: 14px;\r\n        padding-top: 80px;\r\n    }\r\n    \r\n    div.txt2 {\r\n        text-align: right;\r\n        font-size: 14px;\r\n        padding-top: 80px;\r\n        font-weight: bold;\r\n    }\r\n</style></p>\r\n<div class=\"tit\">DECLARA&Ccedil;&Atilde;O DE CONCLUS&Atilde;O DOS SERVI&Ccedil;OS</div>\r\n<div class=\"txt1\">Eu, #nome_gerente#, matr&iacute;cula n&ordm; #matricula#, no uso das atribui&ccedil;&otilde;es  do cargo de #cargo#, declaro para os devidos fins, que o(s)  material(is) e/ou servi&ccedil;o(s) correspondente(s) ao evento N&ordm; #codigo_evento#,  Ordem(ns) de Servi&ccedil;o(s) N&ordm; #codigo_os#, foi(ram) recebido(s) e/ou  prestado(s), liberando-se o processo para pagamento.</div>\r\n<div class=\"txt2\">#cidade#, #estado#, #dt_aprovacao#.</div>', '02.09');
INSERT INTO `db_pir_grc`.`grc_parametros` (`codigo`, `descricao`, `ativo`, `html`, `detalhe`, `classificacao`) VALUES ('evento_declaracao_modelo_re_cab', 'Modelo da Declaração na Prestação de Contas pelo Responsável do Evento (Cabeçalho)', 'S', 'S', '<div style=\"text-align: center;\"><br />\r\n<img src=\"http://pir.ba.sebrae.com.br/sebrae_grc/admin/imagens/rel_logo_sebrae.png\" alt=\"\" /></div>', '02.10');
INSERT INTO `db_pir_grc`.`grc_parametros` (`codigo`, `descricao`, `ativo`, `html`, `detalhe`, `classificacao`) VALUES ('evento_declaracao_modelo_re_rod', 'Modelo da Declaração na Prestação de Contas pelo Responsável do Evento (Rodape)', 'S', 'S', '<p><style type=\"text/css\">\r\n    div.footer_txt1 {\r\n        font-size: 12px;\r\n        font-style: italic;\r\n    }\r\n\r\n    div.footer_txt2 {\r\n        text-align: right;\r\n        font-size: 12px;\r\n        font-style: italic;\r\n        padding-top: 20px;\r\n        padding-bottom: 20px;\r\n    }\r\n</style></p>\r\n<div class=\"footer_txt1\">Este &eacute; um documento gerado eletronicamente pelo Sistema de Gest&atilde;o de Finan&ccedil;as GFI, ap&oacute;s a  <b>autoriza&ccedil;&atilde;o de pagamento</b>, realizada pelo Gerente/Adjunto da Unidade Regional respons&aacute;vel pela realiza&ccedil;&atilde;o do evento.</div>\r\n<div class=\"footer_txt2\">C&oacute;digo de Autenticidade: #md5#</div>\r\n<div style=\"text-align: center;\"><img src=\"http://pir.ba.sebrae.com.br/sebrae_grc/admin/imagens/rel_rodape.png\" alt=\"\" /></div>', '02.11');

-- homologacao
-- sala