CREATE TABLE `plu_helpdesk_interacao` (
  `idt` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `login` varchar(255) DEFAULT NULL,
  `datahora` datetime DEFAULT NULL,
  `ip` varchar(45) DEFAULT NULL,
  `anonimo_nome` varchar(120) DEFAULT NULL,
  `anomimo_email` varchar(120) DEFAULT NULL,
  `latitude` decimal(15,9) DEFAULT NULL,
  `longitude` decimal(15,9) DEFAULT NULL,
  `titulo` varchar(120) NOT NULL,
  `descricao` text NOT NULL,
  `macroprocesso` varchar(45) DEFAULT NULL,
  `protocolo` varchar(45) NOT NULL,
  `nome` varchar(120) DEFAULT NULL,
  `email` varchar(120) DEFAULT NULL,
  `navegador` varchar(1000) DEFAULT NULL,
  `tipo_dispositivo` varchar(255) DEFAULT NULL,
  `modelo` varchar(255) DEFAULT NULL,
  `status` char(1) NOT NULL DEFAULT 'A',
  `tipo_solicitacao` char(2) NOT NULL DEFAULT 'NA',
  `data_envio_email_helpdesk` datetime DEFAULT NULL,
  `mandou_email_helpdesk` varchar(120) DEFAULT NULL,
  `complemento` text,
  `idt_helpdesk_interacao` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`idt`),
  UNIQUE KEY `iu_protocolo` (`protocolo`),
  KEY `ix_login` (`login`,`datahora`),
  KEY `ix_datahora` (`datahora`,`login`),
  KEY `ix_ip` (`ip`),
  KEY `ix_macroprocesso` (`macroprocesso`),
  KEY `FK_plu_helpdesk_interacao_1` (`idt_helpdesk`),
  CONSTRAINT `FK_plu_helpdesk_interacao_1` FOREIGN KEY (`idt_helpdesk_interacao`) REFERENCES `plu_helpdesk_interacao` (`idt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

